name: haskellbooks

dependencies:
  - base >= 4.7 && <5
  # - text
  - split
  - random
  - containers
  - text
  - bytestring
  - QuickCheck
  - quickcheck-instances
  - http-conduit

default-extensions: OverloadedStrings

library:
  source-dirs: src

executables:
  haskellbooks-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    # - -Wall
    dependencies:
    - haskellbooks

tests:
  haskellbooks-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskellbooks